# Generated by Django 4.2.15 on 2024-09-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='vat_eik',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
